site_name: EdiabasX SGBD Reference
site_url: https://emdzej.github.io/ediabasx-docs-sgbd/
repo_url: https://github.com/emdzej/ediabasx-docs-sgbd

theme:
  name: material
  palette:
    scheme: slate
    primary: blue

plugins: []

nav:
  - Home: index.md
  - About: about.md
  - Summary: summary.md
